$ErrorActionPreference="Stop"
if($env:ALTIORA_PATCH -ne "1"){ throw "ALTIORA_PATCH=1 requis (utiliser tools\patch_runner.ps1)" }

$p = Join-Path (Get-Location).Path "tools\snapshot_double_backup_C.ps1"
if(-not (Test-Path -LiteralPath $p)){ throw "FAIL-CLOSED: tools\snapshot_double_backup_C.ps1 introuvable." }

# Fail-closed: ensure we're editing our ABP snapshot script family
$old = Get-Content -LiteralPath $p -Encoding UTF8 -Raw
if(($old -notmatch "ABP_SNAPSHOT_DOUBLE_BACKUP_C_") -and ($old -notmatch "Snapshot C \\+ double sauvegarde")){
  throw "FAIL-CLOSED: snapshot_double_backup_C.ps1 ne semble pas être notre version (refuse overwrite)."
}

$b64 = "IyBBbHRpb3JhIEJhY2t1cCBQcm8KIyBBQlBfU05BUFNIT1RfRE9VQkxFX0JBQ0tVUF9DX1YyCiMgU25hcHNob3QgQyArIGRvdWJsZSBzYXV2ZWdhcmRlIHZlcnMgRjpcQUJQX1NOQVBTSE9UUyBldCBIOlxBQlBfU05BUFNIT1RTCiMgLSBTYW5zIGJhY2t0aWNrcyAow6l2aXRlIGJ1ZyBDb21wcmVzcy1BcmNoaXZlKQojIC0gRWNyaXQgdW4gWklQIGRhbnMgX291dFxzbmFwc2hvdHMKIyAtIEV4Y2x1dCBfb3V0XHNuYXBzaG90c1wqIHBvdXIgw6l2aXRlciBhdXRvLWluY2x1c2lvbgojIC0gQ3LDqcOpIGxlcyBkb3NzaWVycyBzdXIgRjovSDogc2kgcHLDqXNlbnRzCgokRXJyb3JBY3Rpb25QcmVmZXJlbmNlID0gIlN0b3AiCgokcmVwbyA9IFJlc29sdmUtUGF0aCAoSm9pbi1QYXRoICRQU1NjcmlwdFJvb3QgIi4uIikKU2V0LUxvY2F0aW9uICRyZXBvIHwgT3V0LU51bGwKCiR0cyA9IEdldC1EYXRlIC1Gb3JtYXQgInl5eXlNTWRkX0hIbW1zcyIKCiRvdXREaXIgPSBKb2luLVBhdGggJHJlcG8gIl9vdXRcc25hcHNob3RzIgpOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSAkb3V0RGlyIHwgT3V0LU51bGwKCiR6aXAgPSBKb2luLVBhdGggJG91dERpciAoIkFCUF9DXyIgKyAkdHMgKyAiLnppcCIpCldyaXRlLUhvc3QgIkNyZWF0aW5nIHNuYXBzaG90OiAkemlwIgoKJGV4Y2x1ZGUgPSBAKCAoSm9pbi1QYXRoICRyZXBvICJfb3V0XHNuYXBzaG90c1wqIikgKQoKQ29tcHJlc3MtQXJjaGl2ZSAtUGF0aCAoSm9pbi1QYXRoICRyZXBvICIqIikgLURlc3RpbmF0aW9uUGF0aCAkemlwIC1Gb3JjZSAtQ29tcHJlc3Npb25MZXZlbCBPcHRpbWFsIC1FeGNsdWRlICRleGNsdWRlCgpXcml0ZS1Ib3N0ICJTbmFwc2hvdCBjcmVhdGVkLiIKCiRkZXN0cyA9IEAoIkY6XEFCUF9TTkFQU0hPVFMiLCAiSDpcQUJQX1NOQVBTSE9UUyIpCgpmb3JlYWNoKCRkIGluICRkZXN0cyl7CiAgIyBkcml2ZSByb290ID0gIkY6XCIgLyAiSDpcIgogICRkcml2ZVJvb3QgPSAkZC5TdWJzdHJpbmcoMCwzKQogIGlmKFRlc3QtUGF0aCAkZHJpdmVSb290KXsKICAgIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlICRkIHwgT3V0LU51bGwKICAgIFdyaXRlLUhvc3QgIkNvcHlpbmcgc25hcHNob3QgdG8gJGQiCiAgICBDb3B5LUl0ZW0gLUxpdGVyYWxQYXRoICR6aXAgLURlc3RpbmF0aW9uICRkIC1Gb3JjZQogIH0gZWxzZSB7CiAgICBXcml0ZS1Ib3N0ICJXQVJOOiBkcml2ZSBtaXNzaW5nIC0+ICRkcml2ZVJvb3QiCiAgfQp9CgpXcml0ZS1Ib3N0ICJTbmFwc2hvdCBkb3VibGUgYmFja3VwIGZpbmlzaGVkLiI="
$fixed = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b64))

Set-Content -LiteralPath $p -Value $fixed -Encoding UTF8
Write-Host "OK: fixed -> tools\snapshot_double_backup_C.ps1 (V2 B64)"
