$ErrorActionPreference="Stop"

if($env:ALTIORA_PATCH -ne "1"){
  throw "ALTIORA_PATCH=1 requis (utiliser patch_runner.ps1)"
}

$root  = (Get-Location).Path
$tools = Join-Path $root "tools"
New-Item -ItemType Directory -Force $tools | Out-Null

$target = Join-Path $tools "selftest_crypto_nonce.ps1"

# selftest script (lignes -> fichier, UTF-8 sans BOM)
$lines = @(
  '[CmdletBinding()]'
  'param('
  '  [int]$N = 25,'
  '  [Parameter(Mandatory=$true)][string]$Password,'
  '  [Parameter(Mandatory=$true)][string]$SourceDir,'
  '  [Parameter(Mandatory=$true)][string]$AltioraPy,'
  '  [string]$OutDir = "C:\Temp",'
  '  [switch]$KeepFiles'
  ')'
  ''
  '$ErrorActionPreference="Stop"'
  ''
  'function Get-AbpSaltNonce([string]$path){'
  '  $b = [IO.File]::ReadAllBytes($path)'
  '  $j0 = [Array]::IndexOf($b, [byte]0x7B) # {'
  '  if($j0 -lt 0){ throw "JSON start '{' introuvable: $path" }'
  ''
  '  $inStr=$false; $esc=$false; $depth=0; $j1=-1'
  '  for($i=$j0; $i -lt $b.Length; $i++){'
  '    $ch=$b[$i]'
  '    if($inStr){'
  '      if($esc){ $esc=$false; continue }'
  '      if($ch -eq 0x5C){ $esc=$true; continue }'
  '      if($ch -eq 0x22){ $inStr=$false; continue }'
  '      continue'
  '    } else {'
  '      if($ch -eq 0x22){ $inStr=$true; continue }'
  '      if($ch -eq 0x7B){ $depth++; continue }'
  '      if($ch -eq 0x7D){'
  '        $depth--'
  '        if($depth -eq 0){ $j1=$i; break }'
  '      }'
  '    }'
  '  }'
  '  if($j1 -lt 0){ throw "Fin JSON '}' introuvable: $path" }'
  ''
  '  $p = $j1 + 1'
  '  if($p + 28 -gt $b.Length){ throw "Pas assez de bytes après JSON: $path" }'
  ''
  '  $salt  = $b[$p..($p+15)]'
  '  $nonce = $b[($p+16)..($p+27)]'
  ''
  '  [PSCustomObject]@{'
  '    File   = $path'
  '    Salt16 = ($salt  | ForEach-Object { $_.ToString("X2") }) -join ""'
  '    Nonce12= ($nonce | ForEach-Object { $_.ToString("X2") }) -join ""'
  '  }'
  '}'
  ''
  'function Run-AltioraPy([string[]]$args){'
  '  & python $AltioraPy @args'
  '  return $LASTEXITCODE'
  '}'
  ''
  'if(!(Test-Path $AltioraPy)){ throw "AltioraPy introuvable: $AltioraPy" }'
  'if(!(Test-Path $SourceDir)){ throw "SourceDir introuvable: $SourceDir" }'
  'New-Item -ItemType Directory -Force $OutDir | Out-Null'
  ''
  '$outs = 1..$N | ForEach-Object { Join-Path $OutDir ("nonce_selftest_{0}.altb" -f $_) }'
  ''
  'if(-not $KeepFiles){'
  '  $outs | ForEach-Object { Remove-Item $_ -Force -ErrorAction SilentlyContinue }'
  '}'
  ''
  'Write-Host ("== ABP selftest crypto nonce/salt (N={0}) ==" -f $N)'
  'Write-Host ("AltioraPy: {0}" -f $AltioraPy)'
  'Write-Host ("SourceDir: {0}" -f $SourceDir)'
  'Write-Host ("OutDir   : {0}" -f $OutDir)'
  ''
  '$sw = [Diagnostics.Stopwatch]::StartNew()'
  'foreach($o in $outs){'
  '  $code = Run-AltioraPy @("backup","-p",$Password,$SourceDir,$o)'
  '  if($code -ne 0){'
  '    Write-Host ("⛔ backup a échoué (exit={0}) -> {1}" -f $code, $o) -ForegroundColor Red'
  '    exit 2'
  '  }'
  '}'
  '$sw.Stop()'
  ''
  '$rows = $outs | ForEach-Object { Get-AbpSaltNonce $_ }'
  '$dupsNonce = $rows | Group-Object Nonce12 | Where-Object { $_.Count -gt 1 }'
  '$dupsSalt  = $rows | Group-Object Salt16  | Where-Object { $_.Count -gt 1 }'
  ''
  'Write-Host ("Durée génération: {0:n2}s" -f $sw.Elapsed.TotalSeconds)'
  ''
  'if($dupsNonce){'
  '  Write-Host ("⛔ DOUBLON(S) NONCE détecté(s): {0}" -f ($dupsNonce | Measure-Object).Count) -ForegroundColor Red'
  '  $dupsNonce | Sort-Object Count -Descending | ForEach-Object { "{0} x{1}" -f $_.Name, $_.Count } | Write-Host'
  '  exit 1'
  '}'
  ''
  'if($dupsSalt){'
  '  Write-Host ("⚠️ Doublon(s) SALT détecté(s): {0}" -f ($dupsSalt | Measure-Object).Count) -ForegroundColor Yellow'
  '}'
  ''
  'Write-Host ("✅ OK: aucun doublon de nonce sur {0} backups." -f $N) -ForegroundColor Green'
  'Write-Host ("✅ OK: aucun doublon de salt sur {0} backups." -f $N) -ForegroundColor Green'
  'exit 0'
)

$content = ($lines -join "`r`n") + "`r`n"
[IO.File]::WriteAllText($target, $content, [Text.UTF8Encoding]::new($false))
Write-Host "OK: selftest ajouté -> $target"
