$ErrorActionPreference="Stop"
if($env:ALTIORA_PATCH -ne "1"){ throw "ALTIORA_PATCH=1 requis (utiliser tools\patch_runner.ps1)" }

$p = Join-Path (Get-Location).Path "tools\snapshot_double_backup_C.ps1"
if(-not (Test-Path -LiteralPath $p)){ throw "FAIL-CLOSED: tools\snapshot_double_backup_C.ps1 introuvable." }

$old = Get-Content -LiteralPath $p -Encoding UTF8 -Raw
if(($old -notmatch "ABP_SNAPSHOT_DOUBLE_BACKUP_C_") -and ($old -notmatch "Snapshot C \\+ double sauvegarde")){
  throw "FAIL-CLOSED: snapshot_double_backup_C.ps1 ne semble pas être notre version (refuse overwrite)."
}

$b64 = "IyBBbHRpb3JhIEJhY2t1cCBQcm8KIyBBQlBfU05BUFNIT1RfRE9VQkxFX0JBQ0tVUF9DX1YzCiMgU25hcHNob3QgQyArIGRvdWJsZSBzYXV2ZWdhcmRlIHZlcnMgRjpcQUJQX1NOQVBTSE9UUyBldCBIOlxBQlBfU05BUFNIT1RTCiMgQ29tcGF0aWJsZSBXaW5kb3dzIFBvd2VyU2hlbGwgNS4xIChwYXMgZGUgLUV4Y2x1ZGUgc3VyIENvbXByZXNzLUFyY2hpdmUpCiMgRXhjbHV0IF9vdXRcc25hcHNob3RzXCogZW4gY29uc3RydWlzYW50IGxhIGxpc3RlIGRlIGZpY2hpZXJzIMOgIGNvbXByZXNzZXIuCgokRXJyb3JBY3Rpb25QcmVmZXJlbmNlID0gIlN0b3AiCgokcmVwbyA9IFJlc29sdmUtUGF0aCAoSm9pbi1QYXRoICRQU1NjcmlwdFJvb3QgIi4uIikKU2V0LUxvY2F0aW9uICRyZXBvIHwgT3V0LU51bGwKCiR0cyA9IEdldC1EYXRlIC1Gb3JtYXQgInl5eXlNTWRkX0hIbW1zcyIKJG91dERpciA9IEpvaW4tUGF0aCAkcmVwbyAiX291dFxzbmFwc2hvdHMiCk5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlICRvdXREaXIgfCBPdXQtTnVsbAoKJHppcCA9IEpvaW4tUGF0aCAkb3V0RGlyICgiQUJQX0NfIiArICR0cyArICIuemlwIikKV3JpdGUtSG9zdCAiQ3JlYXRpbmcgc25hcHNob3Q6ICR6aXAiCgojIEJ1aWxkIGZpbGUgbGlzdCBleGNsdWRpbmcgX291dFxzbmFwc2hvdHNcKgokc25hcHNob3RzRGlyID0gKEpvaW4tUGF0aCAkcmVwbyAiX291dFxzbmFwc2hvdHMiKQokZmlsZXMgPSBHZXQtQ2hpbGRJdGVtIC1MaXRlcmFsUGF0aCAkcmVwbyAtUmVjdXJzZSAtRmlsZSAtRm9yY2UgLUVycm9yQWN0aW9uIFN0b3AgfAogIFdoZXJlLU9iamVjdCB7CiAgICAjIEV4Y2x1ZGUgYW55dGhpbmcgdW5kZXIgX291dFxzbmFwc2hvdHMKICAgICgkXy5GdWxsTmFtZSAtbm90bGlrZSAoJHNuYXBzaG90c0RpciArICJcKiIpKQogIH0gfAogIFNlbGVjdC1PYmplY3QgLUV4cGFuZFByb3BlcnR5IEZ1bGxOYW1lCgppZigtbm90ICRmaWxlcyAtb3IgJGZpbGVzLkNvdW50IC1lcSAwKXsKICB0aHJvdyAiTm8gZmlsZXMgdG8gY29tcHJlc3MgKHVuZXhwZWN0ZWQpLiIKfQoKQ29tcHJlc3MtQXJjaGl2ZSAtTGl0ZXJhbFBhdGggJGZpbGVzIC1EZXN0aW5hdGlvblBhdGggJHppcCAtRm9yY2UgLUNvbXByZXNzaW9uTGV2ZWwgT3B0aW1hbApXcml0ZS1Ib3N0ICJTbmFwc2hvdCBjcmVhdGVkLiIKCiRkZXN0cyA9IEAoIkY6XEFCUF9TTkFQU0hPVFMiLCAiSDpcQUJQX1NOQVBTSE9UUyIpCmZvcmVhY2goJGQgaW4gJGRlc3RzKXsKICAkZHJpdmVSb290ID0gJGQuU3Vic3RyaW5nKDAsMykKICBpZihUZXN0LVBhdGggJGRyaXZlUm9vdCl7CiAgICBOZXctSXRlbSAtSXRlbVR5cGUgRGlyZWN0b3J5IC1Gb3JjZSAkZCB8IE91dC1OdWxsCiAgICBXcml0ZS1Ib3N0ICJDb3B5aW5nIHNuYXBzaG90IHRvICRkIgogICAgQ29weS1JdGVtIC1MaXRlcmFsUGF0aCAkemlwIC1EZXN0aW5hdGlvbiAkZCAtRm9yY2UKICB9IGVsc2UgewogICAgV3JpdGUtSG9zdCAiV0FSTjogZHJpdmUgbWlzc2luZyAtPiAkZHJpdmVSb290IgogIH0KfQoKV3JpdGUtSG9zdCAiU25hcHNob3QgZG91YmxlIGJhY2t1cCBmaW5pc2hlZC4i"
$fixed = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b64))

Set-Content -LiteralPath $p -Value $fixed -Encoding UTF8
Write-Host "OK: fixed -> tools\snapshot_double_backup_C.ps1 (V3 PS5.1)"
